[build]
    base = "./"

[build.environment]
    NETLIFY_USE_YARN = "true"

[context.deploy-preview]
    ignore = "node -e 'process.exitCode = process.env.BRANCH.includes(\"dependabot\") ? 0 : 1' && gt diff --quiet $CACHED_COMMIT_REF $COMMIT_REF packages" 