blank_issues_enabled: true
contact_links:
  - name: Squiggle GitHub Discussions
    url: https://github.com/quantified-uncertainty/squiggle/discussions
    about: Please propose and discuss new features here. Remember to search for your idea before posting a new topic!
