blank_issues_enabled: true
contact_links:
  - name: Ideas and feature requests - Squiggle Discussions on GitHub
    url: https://github.com/quantified-uncertainty/squiggle/discussions
    about: Please propose and discuss new features here. Remember to search for your idea before posting a new topic! Where would you like to see Squiggle go over the next few months, several months, or few years?
