[build]
    base = "packages/website/"
    publish = "build/"
    build = "cd ../squiggle-lang && yarn build && cd ../website && yarn build"
    # ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ../components ../squiggle-lang"