[build]
    base = "packages/website/"
    command = "cd ../squiggle-lang && yarn build && cd ../website && yarn build"
    publish = "build/"
    # ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ../components ../squiggle-lang"