[build]
    publish = "packages/website/build/"
    build = "cd packages/squiggle-lang && yarn build && cd ../website && yarn build"
    # ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF packages/website packages/components packages/squiggle-lang"