[build]
    publish = "packages/components/storybook-static/"
    build = "cd packages/squiggle-lang && yarn build && cd ../components && yarn build"
    ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF packages/components packages/squiggle-lang"
