[build]
    base = "packages/components/"
    command = "cd ../squiggle-lang && yarn build && cd ../components && yarn build"
    publish = "storybook-static/"
    ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ../squiggle-lang"

[build.environment]
    NETLIFY_USE_YARN = "true"