name: Run Release Please

on:
  push:
    branches:
      - develop

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v2
        id: release
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          default-branch: develop
